// app/api/images/route.js
import { insert, query } from "@/lib/db";
import formidable from "formidable";
import fs from "fs";
import { NextResponse } from "next/server";
import path from "path";

// const config = {
//   api: {
//     bodyParser: false, // required for formidable
//   },
// };

const UPLOAD_DIR = path.join(process.cwd(), "public", "uploads");
const MAX_BYTES = 1 * 1024 * 1024; // 1 MB
const ALLOWED = [
  "image/png",
  "image/jpeg",
  "image/jpg",
  "image/svg+xml",
  "image/x-icon",
  "image/vnd.microsoft.icon",
];

const ensureUploadDir = () => {
  if (!fs.existsSync(UPLOAD_DIR)) {
    fs.mkdirSync(UPLOAD_DIR, { recursive: true });
  }
};

const parseForm = (req) =>
  new Promise((resolve, reject) => {
    const form = formidable({
      multiples: false,
      maxFileSize: MAX_BYTES,
      uploadDir: UPLOAD_DIR,
      keepExtensions: true,
      filename: (name, ext, part) => {
        // generate friendly unique filename: timestamp-random.ext
        const safeExt = ext || path.extname(part.originalFilename || "") || "";
        const base = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
        return `${base}${safeExt}`;
      },
    });

    form.parse(req, (err, fields, files) => {
      if (err) {
        return reject(err);
      }
      resolve({ fields, files });
    });
  });

export async function GET(request) {
  // Query params: ?q=search&limit=24&page=1
  try {
    const url = new URL(request.url);
    const q = url.searchParams.get("q") || "";
    const limit = parseInt(url.searchParams.get("limit") || "24", 10);
    const page = Math.max(1, parseInt(url.searchParams.get("page") || "1", 10));
    const offset = (page - 1) * limit;

    let where = "";
    const params = [];
    if (q) {
      where = "WHERE name LIKE ? OR alt LIKE ? OR img LIKE ?";
      params.push(`%${q}%`, `%${q}%`, `%${q}%`);
    }

    // safe query helper usage (insert your project's query helper)
    const rows = await query("images", where + ` ORDER BY id DESC LIMIT ?, ?`, [
      ...params,
      offset,
      limit,
    ]);
    // Count total
    const totalRes = await query(
      "images",
      where ? "WHERE name LIKE ? OR alt LIKE ? OR img LIKE ?" : "",
      where ? params : [],
      undefined
    );
    // note: query helper's response for count depends on implementation; fallback to length
    const total = Array.isArray(totalRes) ? totalRes.length || 0 : 0;

    return NextResponse.json({ success: true, data: rows || [], page, limit, total });
  } catch (err) {
    console.error("GET /api/images error:", err);
    return NextResponse.json(
      { success: false, error: err.message || String(err) },
      { status: 500 }
    );
  }
}

export async function POST(request) {
  try {
    ensureUploadDir();

    const { fields, files } = await parseForm(request);

    // Expect single file field named 'file'
    const file = files?.file;
    if (!file) {
      return NextResponse.json({ success: false, error: "No file uploaded" }, { status: 400 });
    }

    // formidable returns file.path
    const { filepath, mimetype, originalFilename, size } = file;
    // validate mime + size
    if (!ALLOWED.includes(mimetype)) {
      // delete uploaded temp file if invalid
      try {
        fs.unlinkSync(filepath);
      } catch (e) {}
      return NextResponse.json({ success: false, error: "File type not allowed" }, { status: 400 });
    }
    if (size > MAX_BYTES) {
      try {
        fs.unlinkSync(filepath);
      } catch (e) {}
      return NextResponse.json(
        { success: false, error: "File too large (max 1 MB)" },
        { status: 400 }
      );
    }

    // file is already saved to UPLOAD_DIR with filename generated by formidable
    const filename = path.basename(filepath); // e.g. 1623abcde.png
    const publicPath = `/uploads/${filename}`;

    // Save record to DB
    const payload = {
      name: originalFilename || filename,
      alt: fields?.alt || originalFilename || filename,
      img: publicPath,
      // created_at handled by DB default
    };

    const inserted = await insert("images", payload);

    return NextResponse.json({
      success: true,
      filename: publicPath,
      inserted,
      record: { id: inserted?.insertId || inserted?.id || null, ...payload },
    });
  } catch (err) {
    console.error("POST /api/images error:", err);
    // If formidable threw because of size limit it may include message
    return NextResponse.json(
      { success: false, error: err.message || String(err) },
      { status: 500 }
    );
  }
}
